[allowlist]
description = "Permite apenas chaves públicas de configuração do SonarCloud"
regexes = [
  '''^sonar\.projectKey=.*$''',
  '''^sonar\.organization=.*$'''
]
paths = [
  '''sonar-project\.properties'''
]
