sonar.projectKey=Wesleysoares7_sistema-ofs
sonar.organization=wesleysoares7
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.tests=frontend/src
sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/prisma/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=backend/src/server.ts,backend/src/middlewares/errorHandler.ts,backend/src/controllers/AvisoController.ts,backend/src/routes/avisos.ts,backend/src/services/AvisoService.ts,backend/src/utils/prisma.ts,frontend/src/main.tsx,frontend/src/pages/**,frontend/src/components/**,frontend/src/layouts/**

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300