sonar.projectKey=SEU_ORG_sistema-ofs
sonar.organization=SEU_ORG
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/prisma/**

sonar.sourceEncoding=UTF-8