sonar.projectKey=Wesleysoares7_sistema-ofs
sonar.organization=wesleysoares7
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/prisma/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=frontend/src/pages/**,frontend/src/components/**,frontend/src/layouts/**

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300